[package]
name = "app"
version = "0.1.0"
authors = ["tktcorporation"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"

google-texttospeech1 = "^2.0"
hyper = "^0.14"
hyper-tls = "^0.5"
hyper-rustls = "^0.22"
serde = "^1.0"
serde_json = "^1.0"
yup-oauth2 = "^5.0"

reqwest = "^0.11.4"

[dependencies.songbird]
version = "0.1.1"
features = ["builtin-queue"]

[dependencies.serenity]
version = "0.10"
features = ["cache", "standard_framework", "voice", "rustls_backend"]

[dependencies.tokio]
version = "1.0"
features = ["macros", "rt-multi-thread"]
