version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build-env
    working_dir: /workspace
    environment:
      - USER=$USER
      - DISCORD_TOKEN=$DISCORD_TOKEN
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=$AWS_REGION
    volumes:
      - .:/workspace:cached
      - target:/workspace/target:cached
    tty: true
  executer:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - USER=$USER
      - DISCORD_TOKEN=$DISCORD_TOKEN
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=$AWS_REGION
  tf:
    image: hashicorp/terraform:1.0.0
    container_name: "terraform"
    working_dir: /workspace
    environment:
      - TF_VAR_billing_id=$TF_VAR_billing_id
    volumes:
      - ./terraform:/workspace:cached
      - gcloud-config:/root/.config
  gcloud:
    entrypoint: "gcloud"
    image: google/cloud-sdk:alpine
    container_name: "gcloud"
    working_dir: /workspace
    volumes:
      - ./terraform:/workspace:cached
      - gcloud-config:/root/.config
  heroku:
    # run `apk add docker` before running heroku commands
    image: sue445/heroku-cli
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock:rw
volumes:
  target:
  gcloud-config:
