version: "3.7"
services:
  app:
    build: ./app
    working_dir: /app
    environment:
      - USER=$USER
      - DISCORD_TOKEN=$DISCORD_TOKEN
    volumes:
      - ./app:/app:cached
      - /app/target
