name: Test

on:
  push:

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build containers
        run: docker-compose build

      - name: Test
        run: docker-compose run app /bin/bash -c "RUST_BACKTRACE=1 cargo test --verbose --all -- --nocapture"